### ISSUE TITLE
trpc.io support

### ISSUE THREAD

**Issue by dhinesh03** [FoalTS/foal#1106]
trpc.io(https://trpc.io/) is gaining lot of attractions.  Any chance to add it to FoalTs in near feature?

**Comment by LoicPoullain** [comment]
Hi @dhinesh03 👋 

I took a look at the documentation of trpc. It looks like the library creates its own server or creates an Express middleware to be added in an Express app. This design is not compatible with the way Foal is built which works independently from Express (or at least for a large majority of the code). Due to this architecture issue, it is very unlikely that Foal will include native support of trpc in the future.
