### ISSUE TITLE
'punycode` deprecation in node-fetch

### ISSUE THREAD

**Issue by kennbuluma** [FoalTS/foal#1267]
If possible, could there be an upgrade to node-fetch version 3 to remedy the punycode deprecation warning?

**Comment by LoicPoullain** [comment]
Unfortunately, `node-fetch` v3 requires ESM modules which make the framework not compile. Do you have a message provided with the deprecating warning? What does it say?

**Comment by kennbuluma** [comment]
I get this message when building or running:

`(node:5665) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use node --trace-deprecation ...` to show where the warning was created).​`.

It is no issue during development, but just an inconvenience when running with pm2.


________________________________

**Comment by LoicPoullain** [comment]
Thanks for the clarification.

I think we can leave things as they are for now. Upgrading to v3 is not possible due to the need to support ES modules and switching to another library would require some work.

In the next major release of Foal, the framework will internally use the native implementation of the `fetch` API instead. We'll have to wait for Foal v5 and the abandonment of Node 18 support for this. Node 18 causes problems during testing with the native `fetch` (see note [here](https://github.com/FoalTS/foal/issues/1223)).

**Comment by LoicPoullain** [comment]
https://github.com/FoalTS/foal/pull/1283
