### ISSUE TITLE
Debug to console

### ISSUE THREAD

**Issue by nobleach** [FoalTS/foal#331]
I see a way to decorate a route in a controller with a `@Log` decorator. Is there a way to do simple log statements like 
```
Log(`UserId is: ${userId}`); 
```
Typically these would be like:
```
logger.debug('foo');
```
in many other frameworks.

My reasoning is that I often have VERY thorough logs at the debug-level (and during development). But very sparse info-level.

**Comment by nobleach** [comment]
Just did some digging and realized that this project is using morgan. So one must bring their own logging solution for anything other than request logging. That's fair.

**Comment by LoicPoullain** [comment]
Hi @nobleach ,

Yes, you can create your own hook to log what you need. For example:
```typescript
@Hook({ user } => {
  console.log(user.id);
});
```

If you want to log the user id only during development or test, you can also rest on the `Config` class. For example:

*The controller*
```typescript
...
@Hook({ user } => {
  if (Config.get('my-config-file', 'log', false) {
    console.log(user.id);
  }
});
...
```

*config/my-config-file.development.json* | *config/my-config-file.test.json*
```json
{
  "log": true
}
```

It is also possible to call a service in the hook if you want to have a `LoggerService`

```typescript
@Hook((ctx, services) => {
  services.get(MyLoggerService).log(ctx.user.id);
});
```

Regarding the `logger.debug('foo');`, it is entirely possible to add this feature in the next release. It could check the `debug` value in `settings.json` (so that the "debug" mode can be enabled in several environments). What do you think?

**Comment by nobleach** [comment]
In my case, I just added winston, and set that up as an app logger. I inject that wherever I need it and I can do `this.logger.info`/`this.logger.error`/`this.logger.debug`, etc.

**Comment by LoicPoullain** [comment]
Oh nice, I didn't know Winston. I added more documentation on the [Logging & Debugging](https://github.com/FoalTS/foal/commit/3c1aceb0581f986ef817ac7648dd7c1d0204e161) page so that new comers have an example.

**Comment by nobleach** [comment]
Cool! Thanks for doing that!
