### ISSUE TITLE
sql scripts after db creation?

### ISSUE THREAD

**Issue by djbeckett** [FoalTS/foal#352]
Is there a way to have an sql script run after the database is created by typeorm? I need some triggers that typeorm doesn't support. For example, one to update 'updatedDateTime' fields in postgres with now() when an exiting record is saved.

**Comment by LoicPoullain** [comment]
I assume that you're talking about table and column creation. By default, FoalTS configures TypeORM so that it updates the database schema on every application launch (`synchronize: true` in `ormconfig.json`). If you use [migrations](https://foalts.gitbook.io/docs/topic-guides/databases/generate-and-run-migrations) (recommended for production), you can add new sql queries to create the table / columns. The `npm run migrations:generate` command creates sql queries in files in `src/migrations`. You may edit these files but I'm not sure it will not introduce some weird behavior in future generations.

I would rather use [TypeORM listeners](http://typeorm.io/#/listeners-and-subscribers) in that case. I haven't used them but I think it's pretty close to the triggers you're looking for. Let me know if I'm wrong.

Regarding your example, if you want to add a `updatedDateTime` column to your table, TypeORM offers a specific decorator to do so: `@UpdateDateColumn`. Is that what you were looking for?

Hope this helps.

**Comment by djbeckett** [comment]
Loic, yes this is very helpful, thank you! I will read up on migrations and TypeORM listeners.

@CreateDateColumn sets a default value in postgres of now(), but @UpdateDateColumn depends on the api providing the timestamp value. Ideally I'd like all timestamps to be db generated. To do that on updateDateTime fields requires a trigger in postgres. That's why I asked.

Dan

**Comment by LoicPoullain** [comment]
May be related to https://github.com/typeorm/typeorm/issues/1082

**Comment by LoicPoullain** [comment]
@djbeckett can I close this issue?
