### ISSUE TITLE
Documentation JWT

### ISSUE THREAD

**Issue by jcpc91** [FoalTS/foal#372]
For better understand add the import statement to all code so for the newer like me will be more easy see where they come from

```
import { JWTRequired } from "@foal/jwt";
import { sign } from 'jsonwebtoken';
@JWTRequired()
class MyController {}

@JWTRequired({ user: fetchUser(User), blackList: isInFile('./blacklist.txt'), cookie: true })
class MyController {}

@JWTRequired({}, { audience: 'foo' })
class MyController {}
```

docs (https://foalts.gitbook.io/docs/topic-guides/authentication-and-access-control/jwt) on setup section idont understand the docs say:

> You must provide a secret or a public key to the hooks. You have two ways to do tha
> - in the **config/default.json** file through the settings.jwt.secretOrPublicKey key

 but the file **config/default.json** doesn't exist only 3 files
- settings.development.json
- settings.json
- settings.production.json
🤷🏼‍♂️

when i try to get de secret key using Config the "get" method need two params like this

`static get(configName: string, propName: string, defaultValue?: number | string | boolean): number | string | boolean | undefined;`

im using 

> import { Config, Context, Post, HttpResponseOK, HttpResponseUnauthorized, logIn } from "@foal/core";

**Comment by LoicPoullain** [comment]
Hi @jcpc91

Thanks for your interest!

> For better understand add the import statement to all code so for the newer like me will be more easy see where they come from
> 
> ```
> import { JWTRequired } from "@foal/jwt";
> import { sign } from 'jsonwebtoken';
> @JWTRequired()
> class MyController {}
> ```

Sounds a good idea. I will pay attention in the future. Do you want to submit a PR on that to fix the JWT doc?

> but the file **config/default.json** doesn't exist only 3 files

I think that you use the version 0.7 of Foal which had a different configuration system. If so, then you can create a file named `jwt.json` and fill it with this content:

```json
{
  "secretOrPublicKey": "your_key"
}
```

... and use the `Config` class like this: `Config.get('jwt', 'secretOrPublicKey')`. Note that if you want to use an environment variable, it will be named `JWT_SECRET_OR_PUBLIC_KEY` in v0.7.

In version 0.8, the configuration system works differently (it's the only breaking change). That's why the file names are different. I wrote a migration guide [here](https://github.com/FoalTS/foal/releases/tag/v0.8.0) to upgrade to the new version. It shouldn't take too long, it took me about 5-10 minutes to migrate my projects from 0.7 to 0.8. I would recommend you to go to v0.8 since further features will be added to this version using the new Config system.

Let me know if you any questions.

**Comment by jcpc91** [comment]
hi thanks for the answer and congratulations for the works.
I would like to help you but idont speak english barely can write thanks to the google translate im pretty sure i would spelling mistakes

**Comment by LoicPoullain** [comment]
Sure. No worries. I was just talking about adding the two imports in the code. ;)

> congratulations for the works

Thank you!

Also, did it solve your problem? Can I close this issue?

**Comment by jcpc91** [comment]
yes solved thanks
