### ISSUE TITLE
Question: Root imports

### ISSUE THREAD

**Issue by pjo336** [FoalTS/foal#434]
Are root import supported? I.e. instead of:
`import  { Foo } from "../../../entities"`

you could do: 

`import { Foo } from "@/entities"`.

**Comment by LoicPoullain** [comment]
This feature is currently not supported. Adding the compiler option `"baseUrl": "src/app"` in `tsconfig.json` will make the build pass with `import { Foo } from "entities"`. But, unfortunately, TypeScript will not convert the path in the build output making node to fail at runtime (*module "entities" not found*)

However, this could be a feature added in the future (cf PR #436). Do you think it's a *must have*? 

A workaround could be also to compile your code with Babel and the modules [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) and [babel-preset-typescript](https://babeljs.io/docs/en/babel-preset-typescript). I have never done it myself but I think it could make root import possible (with a bit of work to set up the environment)

**Comment by pjo336** [comment]
Hey, I don't think it's entirely `must hav`. I am just taking Foal for a spin, and trying out things we do at my work. We actually have people who love it, and people who hate it, so I wouldn't want to force it into your app when a user can just add it themselves.

We do this using [module-alias](https://www.npmjs.com/package/module-alias) lib to alter the routes and run ([ts-node](https://www.npmjs.com/package/ts-node)) and build time. Probably not the safest operation :P

**Comment by squareloop1** [comment]
Would love this too. I currently do it with path aliases in the tsconfig.json and handle the output with module-alias.

It just makes the imports cleaner. Sadly it seems like the Foal CLI has a problem with it too when running scripts. It seems like the CLI is not able to find the aliased path modules.

**Comment by LoicPoullain** [comment]
> Would love this too. I currently do it with path aliases in the tsconfig.json and handle the output with module-alias.
> 
> It just makes the imports cleaner. Sadly it seems like the Foal CLI has a problem with it too when running scripts. It seems like the CLI is not able to find the aliased path modules.

@squareloop1 can you give an example on how you run a Foal script with the CLI and module-alias?

**Comment by squareloop1** [comment]
> > Would love this too. I currently do it with path aliases in the tsconfig.json and handle the output with module-alias.
> > It just makes the imports cleaner. Sadly it seems like the Foal CLI has a problem with it too when running scripts. It seems like the CLI is not able to find the aliased path modules.
> 
> @squareloop1 can you give an example on how you run a Foal script with the CLI and module-alias?

I just run the normal `foal run my-script` after building my app and my scripts with `npm run build:app` and `npm run build:scripts`
I had configured the baseUrl in the tsconfig.json to `./src/app` and module-alias configured and imported in the main entrypoint to convert the paths to the output build-directory.
App worked fine this way but the CLI did not find the modules when using a module with such imports in the script. 
I returned my codebase to normal imports without aliases now and its working perfectly fine. This is definetly not a high priority feature to have, would be just some sugar on top :)

**Comment by pjo336** [comment]
If this was something people wanted, I could definitely look into implementing it. I would just need a decision on what the base path should look like.

At my work we do `@` aliased to src so `src/services` would be `@/services`.

At home I generally do `~` aliased to the root, so i can import test helper files and factories in tests with `~/tests/factories` or something

**Comment by LoicPoullain** [comment]
Sorry for the late reply. Here where the problem comes from:
- When we run the app (`npm run develop`, `npm start`), node executes the file `src/index.ts` as entry point. So with the `import 'module-alias/register';` at the beginning, root imports are properly resolved.
- When we execute `foal run <my-script>`, the CLI node process only `requires` the shell script file. It does not go through `src/index.ts`, this is why the root imports do not work in this case.

One way to get around this is to add the `import 'module-alias/register';` at the beginning of each script. This way, they will be resolved correctly.

At some point, FoalTS will have a complete CLI with commands such as `foal build` and `foal develop` that can be customized with a configuration file `foal.yml` (the PR #436 gives an idea of what it might look like). There will be probably a `root import` option that will convert the root paths directly at compilation.

I think that for now we can just add a new page `Cookbook > Root Imports` in the documentation so that developers can quickly set up root imports.

@pjo336 do you feel like to write documentation on this?

I personally got this code working:


*tsconfig.json*
```json
{
  "compilerOptions": {
    "baseUrl": "src",
    ...
  }
}
```

*package.son*
```json
{
  ...
   "_moduleDirectories": ["./build"]
}
```

*src/index.ts*
```typescript
import 'module-alias/register';
...
```

*src/scripts/create-user.ts*
```typescript
import 'module-alias/register';
...
```

*src/app/controllers/api.controller (example of root imports)*
```typescript
import { User } from 'app/entities';
```

**Comment by LoicPoullain** [comment]
Documentation added!
