### ISSUE TITLE
twig is not a template engine.

### ISSUE THREAD

**Issue by chiqui3d** [FoalTS/foal#441]
Hello I'm started and I want to use twig template system, but I get an error:

`Error: twig is not a template engine.`

This package https://github.com/twigjs/twig.js#usage-with-express in Nest worked correctly. I suppose this error will also occur for handlebars

Config default:

`templateEngine: twig`

I also do not see any option to set default templates/views directory.

Thanks

**Comment by chiqui3d** [comment]
I've finally got it this way:

ExampleController extended the BaseController:

```
import { Get, HttpResponseNotFound } from '@foal/core';
import { Domain } from '../Entity/Domain';
import { getRepository } from 'typeorm';
import {BaseController} from "../base.controller";

export class ExampleController extends BaseController {

  @Get('/')
  async index(ctx) {
    const domain = await getRepository(Domain).findOne(1);
    if(!domain){
      return new HttpResponseNotFound('Not Domain Found');
    }
    return this.render('index.twig',{title: 'Hello Word', domain: domain});
  }

}
```
BaseController
```

import { promisify } from 'util';
import { readFile } from 'fs';
import { join } from 'path';
import {HttpResponseOK} from "@foal/core";

export class BaseController {

  async render(view: string,options: object){
    const render = await this.renderView(view,options);
    return new HttpResponseOK(render);
  }

  async renderView(view: string,options: object) {
    const Twig = require('twig');
    const data = await promisify(readFile)(join(__dirname, '../templates/'+view), 'utf8');
    const template = Twig.twig({
      data: data
    });

    return template.render(options)
  }

}
```

**Comment by LoicPoullain** [comment]
> This package https://github.com/twigjs/twig.js#usage-with-express in Nest worked correctly. I suppose this error will also occur for handlebars

The way Express and FoalTS render templates is quite different, that's why it is not working.

> `templateEngine: twig`

Currently, FoalTS only support packages that export a `renderToString` function (for example `@foal/ejs`)  with this signature:

```typescript
renderToString(template: string, locals: object): string;
```

The next version of FoalTS ([version 1.0.0](#431)) will also support asynchronous `renderToString` functions.

It's not the first time someone's asking for Twig support so I guess we can add its support in a next release. I'll open an issue for that. 

Maybe the best thing to do would be also to support out-of-the-box Express compatible template engines?

**Comment by LoicPoullain** [comment]
Closing this in favor of #445
