### ISSUE TITLE
[Logger] Support the "none" option

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#475]
# Issue

FoalTS uses [morgan](https://www.npmjs.com/package/morgan) under the hood to log HTTP requests. We may want to disable this global logger in certain situations:
- when running E2E tests
  <img width="434" alt="github" src="https://user-images.githubusercontent.com/13604533/61278334-509e1500-a7b4-11e9-987d-f6e093cbbf04.png">
- when deploying the application to a Cloud provider which takes care of the logging itself (for example AWS Lambda with Cloud Watch).

Currently this is not possible.

# Resources

FoalTS: https://github.com/FoalTS/foal/blob/master/docs/utilities/logging-and-debugging.md
Morgan: https://www.npmjs.com/package/morgan

# Solution

When we specify the logger format in the environment variable `SETTINGS_LOGGER_FORMAT` or in a configuration file, we can accept a `none` format to disable the logging.

*Example with config/default.json*
```json
{
  ...
  "settings": {
    "loggerFormat": "none"
  }
}
```

# Implementation

Files to update:
- foal/packages/core/src/express/create-app.ts (unfortunately we won't be able add a test on this one)
- The files `e2e.json` and `e2e.yml` in `packages/cli/src/generate/specs` and `packages/cli/src/generate/templates`
- https://github.com/FoalTS/foal/blob/master/docs/utilities/logging-and-debugging.md

@yaaminu, do you want to submit a PR on this?

**Comment by yaaminu** [comment]
@LoicPoullain Yes I will.

**Comment by LoicPoullain** [comment]
Feature added in August release.

**Comment by pdeak** [comment]
Am I the only one having the following issue with this option: When I set settings.loggerFormat to "none", I literally get the word "none" logged to the console over and over, for every logging attempt. So rather than turning off logging it still logs every single time, but it simple logs the word none.

To verify that I'm not going crazy, I can change that config to "tiny" or any other format supported by morgan and it works fine, setting the log format as expected.
