### ISSUE TITLE
Deploy an application

### ISSUE THREAD

**Issue by TekinGomes37** [FoalTS/foal#504]
I would like to know how to publish a foal app, or node in general (HTTPS). In the documentation does not speak much.

**Comment by OrkhanAlikhanov** [comment]
Did you see https://foalts.gitbook.io/docs/topic-guides/cloud/aws-beanstalk?

**Comment by TekinGomes37** [comment]
I saw, but it is with AWS and firebase, I would like to deploy normal, without going through these cloud services, for example how to deploy with nginx.

**Comment by LoicPoullain** [comment]
Hi @TekinGomes37,

Thank you for your interest in FoalTS!

https://foalts.gitbook.io/docs/topic-guides/deployment-and-environments/ship-to-production

Does this help? Have you also considered using another cloud provider such as Heroku?

The documentation does not have a tutorial on how to deploying a FoalTS application to a simple vm because there is no *simple answer* on this. Using a PaaS solution (beanstalk, Heroku, Firebase, GCP, Azure WebApps, etc) has the advantage of taking care of the firewall, using a load balancer for scalability, keeping an up-to-date and secure version of node, etc.

However, if you'd like to go with a *normal* deploy, deploying a FoalTS application is exactly the same as deploying a simple Node.JS app. There are many tutorials/subjects on this subject on the Internet.

I personally use `pm2` because it is really intuitive and easy to manipulate (`pm2 start ./build/index.js`). Regarding HTTPS, you will need to use a certificate. I have never generated one myself, so I won't be able to help much on this.
