### ISSUE TITLE
Validate query hook doesn't not accept function

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#511]
As the title said

**Comment by LoicPoullain** [comment]
In which situation would you like to have a function instead of a simple object?

**Comment by kingdun3284** [comment]
> In which situation would you like to have a function instead of a simple object?

I think it should be kept consistency? As most of the hooks accept function after the june release

**Comment by LoicPoullain** [comment]
Oh, do you mean a function to access the controller instance? If so, it is not possible *by design* (this is why `@ValidateQueryParam`, `@ValidatePathParam`, `@ValidateCookie` and `@ValidateHeader` were introduced). I don't remember why, but we were stuck because of the architecture of FoalTS and the way the `ValidateQuery` hook definition differs from the "philosophy" of OpenAPI specification.
