### ISSUE TITLE
npm run develop gives TS Error about excessive stack depth

### ISSUE THREAD

**Issue by silentworks** [FoalTS/foal#528]
I get the error below when I run `npm run develop` on a fresh project setup.

It turns out the issue is related to the latest Typescript, but I though I would open this here so that others are aware if they should run into this issue.

https://github.com/typeorm/typeorm/issues/3194

![Screenshot 2019-09-01 14 14 53](https://user-images.githubusercontent.com/79497/64082812-ae56d400-cd04-11e9-9afa-b0ba7d342dde.png)

**Comment by webcoderkz** [comment]
lol, i just decided to give a try to this framework, and even `npm run develop` didn't work, nice start.

**Comment by OrkhanAlikhanov** [comment]
https://github.com/typeorm/typeorm/issues/3194#issuecomment-526037271

Try this solution. Should work.

**Comment by webcoderkz** [comment]
@OrkhanAlikhanov turning an error off - worked, but would they actually fix it?

**Comment by OrkhanAlikhanov** [comment]
That's actually issue of typeorm. There is nothing to do on foalts part (except maybe shipping with previous version of typescript), wait for typeorm to fix it I'd say

**Comment by webcoderkz** [comment]
As i understand from an error text, it is related to a mongo, right?

**Comment by LoicPoullain** [comment]
Thank you for reporting this @silentworks and for providing support @OrkhanAlikhanov .

As Orkhan said, this issue is specific to TypeORM (which supports MongoDB, hence this message) and we will need TypeORM team to fix it before using TS@3.6.

However it is possible to downgrade to version `3.5` simply with `npm i typescript@3.5`.

This is not the first time that we had such an issue when a new TypeScript version is released. I'll make `foal createapp` use `3.5` by default in every new project so that we don't get any more "surprises" in the future.

**Comment by LoicPoullain** [comment]
Fixed in version 1.1.0 (released soon).
