### ISSUE TITLE
Ajv $ref problem

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#552]
I found that the ajv can't resolve
```
$ref:#/components/schemas/someSchema
```
which is supposed to be supported by openapi 3. After I studied some of the source code, I found that foal didn't adding the whole openapi.json schema when initializing the ajv instance, but only validate against a part of the schema.

**Comment by kingdun3284** [comment]
I am currently using a simple workaround. I generate the components schema and store in a file. Then compile it into ajv when start up the server. Then modify the validation hook, so that $ref: #/components/schemas/someSchema is transformed into ajvschemaname/components/schemas/someSchema in run time. I hope there will be an official solution. What do you think?@LoicPoullain

**Comment by LoicPoullain** [comment]
This problem is really annoying I agree and it is also complicated to solve. I'm afraid it involves to review some parts of the internal architecture of `@foal/core` and so will have to wait version 2.

There are other workarounds that I see (but which are not that great):

> I have not tested the code. The syntax might be a bit different.

**Solution 1**

Do not use the `$ref` key but share a plain JS object between the decorators.

**Inconvenient:** It is not UX friendly when using Swagger UI.

```typescript
const userSchema = { ... };

export class UserController {
   @ValidateBody(userSchema)
   createUser(ctx) {
      // ...
   }

   @ValidateBody(userSchema)
   createUser(ctx) {
      // ...
   }
}
```

**Solution 2**

Split hooks and OpenAPI decorators.

**Inconvenient:** This introduces a lot of redundant code.

```typescript
import { getAjvInstance } from '@foal/core';

const userSchema = { ... };

// Add the schema to Ajv using getAjvInstance()

@ApiDefineSchema('user', userSchema);
export class UserController {
   @ValidateBody({ $ref: 'ajv path', { openapi: false })
   @ApiRequestBody({ $ref: 'openapi path' })
   createUser(ctx) {
      // ...
   }

   @ValidateBody({ $ref: 'ajv path', { openapi: false })
   @ApiRequestBody({ $ref: 'openapi path' })
   createUser(ctx) {
      // ...
   }
}
```

*Solution 3*

Maybe it is possible to play with Ajv and the `$id` key to get the same "ajv path" and "openapi path" (`#/components/schemas/someSchema`). Then we could register the schema with `getAjvInstance`.

Any thoughts on this?

**Comment by kingdun3284** [comment]
> This problem is really annoying I agree and it is also complicated to solve. I'm afraid it involves to review some parts of the internal architecture of `@foal/core` and so will have to wait version 2.
> 
> There are other workarounds that I see (but which are not that great):
> 
> > I have not tested the code. The syntax might be a bit different.
> 
> **Solution 1**
> 
> Do not use the `$ref` key but share a plain JS object between the decorators.
> 
> **Inconvenient:** It is not UX friendly when using Swagger UI.
> 
> ```ts
> const userSchema = { ... };
> 
> export class UserController {
>    @ValidateBody(userSchema)
>    createUser(ctx) {
>       // ...
>    }
> 
>    @ValidateBody(userSchema)
>    createUser(ctx) {
>       // ...
>    }
> }
> ```
> 
> **Solution 2**
> 
> Split hooks and OpenAPI decorators.
> 
> **Inconvenient:** This introduces a lot of redundant code.
> 
> ```ts
> import { getAjvInstance } from '@foal/core';
> 
> const userSchema = { ... };
> 
> // Add the schema to Ajv using getAjvInstance()
> 
> @ApiDefineSchema('user', userSchema);
> export class UserController {
>    @ValidateBody({ $ref: 'ajv path', { openapi: false })
>    @ApiRequestBody({ $ref: 'openapi path' })
>    createUser(ctx) {
>       // ...
>    }
> 
>    @ValidateBody({ $ref: 'ajv path', { openapi: false })
>    @ApiRequestBody({ $ref: 'openapi path' })
>    createUser(ctx) {
>       // ...
>    }
> }
> ```
> 
> _Solution 3_
> 
> Maybe it is possible to play with Ajv and the `$id` key to get the same "ajv path" and "openapi path" (`#/components/schemas/someSchema`). Then we could register the schema with `getAjvInstance`.
> 
> Any thoughts on this?
I have tried all solution before.
Solution 1 is bad. It will generate a lot of inline object when using openapi generator to generate documents and sdk.

Solution 2 is by far the best solution currently, but turn the openapi option of validation hook meaningless and cause a lot of redundant code.

Solution 3 as far as I known is not possible, as ajv follows JSON schema which means # = current schema object. Unless you do something like:

validate-body.hook.ts
```
...
import openapi from "openapi.json" //Statically generated openapi specification
function validate(this: any, ctx: Context) {
    const ajvSchema = isFunction(schema) ? schema(this) : schema;
    if (!ajv.validate({ajvSchema, components: openapi.components } }, ctx.request.body)) {
      return new HttpResponseBadRequest({ body: ajv.errors });
    }
  }
...


```
But this will cause a performance issue obviously.

**Comment by LoicPoullain** [comment]
## The problem

@kingdun3284 I've been working for some days on this issue. If I sum up properly, there are two issues that we are facing here.

### Issue 1

When using AJV validation hooks, we would like to register additional schemas to the AJV instance and reference them in the hooks.

```typescript
const productSchema = {
  // ...
}

@ValidateBody({
  $ref: 'path of productSchema'
})
```

**Workaround:** Currently this can be done manually by importing `getAjvInstance` and calling the `addSchema` method: `getAjvInstance().addSchema(productSchema, 'path of productSchema')`

### OpenAPI

> *This section is not an issue. This is working properly*.

When using OpenAPI decorators, we can register additional schemas and reference them.

```typescript
const productSchema = {
  // ...
}

@ApiDefineSchema('product', productSchema)
@ApiDefineRequestBody({
  content: {
    'application/json': {
      $ref: '#/components/schemas/product'
    }
  },
  required: true
})
```

### Issue 2

When we use AJV validation hooks with `settings.openapi.useHooks: true` to generate automatically the OpenAPI spec from the validation schemas, we would like to do the same.

```typescript
const productSchema = {
  // ...
}

@ApiDefineSchema('product', productSchema)
@ValidateBody({
  $ref: '#/components/schemas/product'
})
```

Currently this is not working.

A workaround is to call `getAjvInstance.addSchema('#/components/schemas/product', productSchema)` but this is not a reliable solution since it does respect the JSON schema specification (as you mentionned before, `# = current schema object`). So this hack could fail in a future version of AJV.

It is also not handy to call `getAjvInstance.addSchema` each time we want to refer a schema.

**Comment by LoicPoullain** [comment]
## Constraints on the solutions

- Validations hooks can reference other schema objects even if OpenAPI is not used in the project.
- JSON schema and OpenAPI specifications are slightly different. We must be able to use two separate schemas/references when needed.
- The new solution should not introduce significant performance issues.
- Referenced schema objects can reference other schema objects (see JSON schema and OpenAPI spec).
- Two schemas with the same name can be declared for two different APIs (for example /api/v1 et /api/v2) without making conflicts.
- We must be able to generate an OpenAPI specification from a shell script.
- The solutions should work accross several npm packages.

**Comment by LoicPoullain** [comment]
## Possible solutions of the issue 1

The solutions presented below solve the first issue, ie they are used in these two situations:

- The application does not use OpenAPI/Swagger.
- The application uses OpenAPI and we are in the situation where the JSON schema specification is different from OpenAPI specification and so we need to define two schemas separately.

### `AppController.schemas`

`AppController` accepts an optional `schemas` array to define AJV schemas.

```typescript
class AppController {
  subControllers = [
    controller('/api', ApiController)
  ];

  schemas = [
    schema('path to product schema', myProductSchema)
  ];
}

class ApiController {
  @Post('/products')
  @ValidateBody({
    $ref: 'path to product schema'
  })
  createProduct() { /* ... */ }
}
```

Pros:
- Easy to use and understand.

Cons:
- The definitions are centralized in one single place which can be harder to manage in bigger applications.
- It adds another special property to the `AppController` (`init`, `handleError`, etc).
- It does not use TypeScript type checking.
- AJV is deeply embedded in the core of the framework.
- Users must know that `schemas` is reserved keyword in `AppController` even if they do not use  or even do not know the `$ref` feature.

### `ValidationService`

Add a `ValidationService` to register the schemas.

*Example 1*
```typescript
class AppController {
  @dependency
  validation: ValidationService;

  subControllers = [
    controller('/api', ApiController)
  ];

  init() {
    this.validation.addSchema('path to product schema', myProductSchema)
  }
}

class ApiController {
  @Post('/products')
  @ValidateBody({
    $ref: 'path to product schema'
  })
  createProduct() { /* ... */ }
}
```

*Example 2*
```typescript
class ApiController {
  @dependency
  validation: ValidationService;

  boot() {
    this.validation.addSchema('path to product schema', myProductSchema)
  }

  @Post('/products')
  @ValidateBody({
    $ref: 'path to product schema'
  })
  createProduct() { /* ... */ }
}
```

Pros:
- In large applications, we can register the schemas in the sub-controllers.
- AJV is not part of the very core of the framework.
- We take advantage of TypeScript type checking.
- Only people looking for the `$ref` feature are concerned with this.

Cons:
- Maybe a bit more complex.
- We may have issues to deal with when using the service accross several npm packages (class dupplicated).

**Comment by LoicPoullain** [comment]
## Solution of the issue 2

Make this code work by itself:
```typescript
const productSchema = {
  // ...
}

@ApiDefineSchema('product', productSchema)
@ValidateBody({
  $ref: '#/components/schemas/product'
})
```

**Comment by LoicPoullain** [comment]
## Possible implementation of the solution of the issue 2

The description below is a summary of the in-depth study that took into account performance considerations, the difficulty/feasability, the amount of work required and the maintainability and testability of the new code.

It is mostly a help for me to implement the feature

### Implementation 1: the framework replaces the values of the $ref keyword in the hooks

*Idea: replace the `$ref` value with another link to the schema to get rid of the `#`.*

Cons:
- Traversing all validation schemas to replace the `$ref` value will probably cause performance issues.
- Schemas need to be registered manually to the AJV instance.
- Errors returned by the validation hook *might* be inconsistent with the OpenAPI document.
- Component schemas can reference other schemas with `#`, so this won't work.

### Implementation 2: use one global AJV schema so that `#` works.

*Idea: build a global AJV schema which contains the OpenAPI component schemas.*

Cons:
- AJV is deeply embedded in the core of the framework.
- OpenAPI and JSON schema are slightly different. This solution does not deal with it.
- Only a part of the application may be described by an OpenAPI document (ex: `/api` is but the pages routes are not).
- Several openAPI documents may co-exist in the same application.
- This implementation would require an initialization step to build the global schema from all the hooks and we would have to manage generated IDs. Supporting hook initialization would introduce certain complexity which I wouldn't go with.

### Implementation 3 (the one chosen): use local AJV schemas

*Idea: keep a local schema in each hook which is compiled the first time the hook is executed. Add the document component schemas to the hook schema.*

I don't think this implementation would lead to peformance issues but we'll have to check.

Pros: the cons of implementation 2

The last difficulty that we have to face is to get the component schemas of the OpenAPI document which the controller belongs to.

For this, an `OpenApiService` can be added to register the OpenApi specifications(s) with their controller instances (then the hook will be able to know which API it belongs to).

> Currently the component schemas are only discovered for the first time at run time when requesting `/openapi.json` (it calls `createOpenApiDocument` in the `SwaggerController`).

#### One way to do this (not chosen)

A boot method in the controller that creates the specs when launching the application and register them into the service.

Cons:
- It is a bit hacky and complexifies the internal OpenAPI code which already complex.
- It only works with one OpenAPI document because the hook cannot know which API it belongs to.

#### The other (right) way (chosen)

Refactor the core code so that the documents (known by `@ApiInfo`) and the app routes are built at the same moment. At this moment the document are registered in the service.

Pros:
- Reduce the amount of code that lives in the framework core. The tree searches are currently dupplicated.
- Several OpenAPI documents can be supported.

Cons:
- Refactorisation of the framework core (sensitive part of the framework).
- Special case for generating a spec for a shell script.

**Comment by LoicPoullain** [comment]
Feature added in v2
