### ISSUE TITLE
Feature Request: Improve failed validation response

### ISSUE THREAD

**Issue by motia** [FoalTS/foal#615]
Hi, I started using the framework today, and I found using it both really fun and productive. I love it :)

I had like to suggest an improvement for the response to requests which fails validation. It would be great if it responded with a 422 response which indicates an UnprocessableEntity but it returns a 400 which indicates a generic error.  I found this issue distracting while coding on the frontend, as I can not determine whether the error is of validation or not.

The change will be simple if we could change the returned status code in the [validate-body.hook](https://github.com/FoalTS/foal/blob/master/packages/core/src/common/hooks/validate-body.hook.ts
)
But for backward compatibility, I guess it would be preferable to use a progressive approach. I will be happy to help with PR.

Thank you for the great framework, cheers!

**Comment by LoicPoullain** [comment]
> Hi, I started using the framework today, and I found using it both really fun and productive. I love it :)

Thanks!

>  It would be great if it responded with a 422 response which indicates an UnprocessableEntity but it returns a 400 which indicates a generic error.

I think the status code 400 is correct here.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) and [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.5.1):
- *The HyperText Transfer Protocol (HTTP) 422 Unprocessable Entity response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.*
- *The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).*

The 400 error may be a bit more generic but I'd rather go for it over 422 because:
- it seems that 400 is more widely used that 422 to build REST APIs (personally, I'd never come across it until today).
- the recent [RFC 7231 specification](https://tools.ietf.org/html/rfc7231) does not include the 422 status anymore.

However, if you need to build a hook that returns a code 422 on validation failure, you have two other options to do so:

- Create your own validation hook. Maybe something like this:
    ```typescript
    class HttpResponseUnprocessableEntity extends HttpResponseClientError {
      statusCode = 422;
      statusMessage = 'UNPROCESSABLE ENTITY';
    }

    function ValidateBody(schema: object): HookDecorator {
      return Hook(ctx => {
        const ajv = getAjvInstance();
        if (!ajv.validate(ajvSchema, ctx.request.body)) {
          return new HttpResponseUnprocessableEntity({ body: ajv.errors });
        }
      });
    }
    ```
- Create a post hook that changes the status code (hacky):

    ```typescript
    @ValidateBody(...)
    @Hook(() => response => {
      if (...) { (response as any).statusCode = 422 };
    })
    ```

**Comment by motia** [comment]
Thank you for the explanation! 
I see you used 400 instead of 422 intentionally. And the solutions you suggested are fairly simple.
