### ISSUE TITLE
createOpenApiDocument() will actually start the server and pause at listening port

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#681]
Having a foal script like this. Execute it by running command foal run generate-openapi-doc and it actually start the server and show ```Listening on port 3001...```.  Command after this is not being excuted.
```typescript
export async function main() {
  const connection = await createConnection();
  const documentPublic = createOpenApiDocument(PublicController);

  writeFileSync('openapiPublic.json', JSON.stringify(documentPublic, null, 2), 'utf8');
  await connection.close();
}
```

**Comment by LoicPoullain** [comment]
@kingdun3284 would it be possible that your `PublicController` file import directly or indirectly `src/index.ts`?

**Comment by kingdun3284** [comment]
Yes, I export something in index.ts and import in the controller.

**Comment by LoicPoullain** [comment]
Ok, this is where the problem comes from. When loading the script, the controller file imports `src/index.ts` which starts the server and causing the script not be executed.

The `src/index.ts` file should not be imported anywhere : it is the file to be used to start the server.  If you have something to share in `index.ts` and `public.controller.ts`, the best way to do it is to move it to another file and import this file from both `index.ts` and `public.controller.ts`.

**Comment by kingdun3284** [comment]
Thanks, you have solved my issue.
