### ISSUE TITLE
[Social auth] Add Microsoft / Azure provider

### ISSUE THREAD

**Issue by yazantahhan** [FoalTS/foal#897]
### Issue

Adding the support for Microsoft accounts in Social authentication.

### Solution and steps

- [ ] Add Microsoft provider.
- [ ] Test Microsoft provider in @foal/examples.

### Checklist

- [ ] Add/update/check docs (code comments and docs/ folder).
- [ ] Add/update/check tests.
- [ ] Update/check the cli generators.

I did a custom Provider for Microsoft accounts and thought that I can add it to the supported list for Foal, so other users can get use of it. 
@LoicPoullain Please let me know what you think and if you have any comments to consider

**Comment by LoicPoullain** [comment]
Thank you for your suggestion @yazantahhan and sorry for the late reply.

The number of providers officially supported by Foal will be kept limited so as to reduce maintenance. This is why Microsoft provider won't be added in the future.

However, if you still wish to publish your provider as a separate package, feel free to let me know so that we can add in the documentation a community link to your repository.
